kind: Secret
apiVersion: v1
metadata:
  name: mongodb-secret
  namespace: chat-app
  labels:
    app: mongodb
    env: production
    version: v1
    owner: riya
    purpose: demo
    created-by: riya
type: Opaque
data:
  jwt-secret: ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKU2IyeGxJam9pUVdSdGFXNGlMQ0pKYzNOMVpYSWlPaUpKYzNOMVpYSWlMQ0pWYzJWeWJtRnRaU0k2SWtwaGRtRkpibFZ6WlNJc0ltVjRjQ0k2TVRjME5UTTBPREEyTWl3aWFXRjBJam94TnpRMU16UTRNRFl5ZlEuWHA3bFk1OEVmY3BMSC1nSF8xUnZ2cG5fLXFiM0FYLXpJU0daMjE0T2lHdwo=